name: Push nginx image to Yandex Cloud
on:
  workflow_dispatch:  # запуск вручную

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Проверяем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4  # обновлена версия

      # 2. Проверка Docker версии
      - name: Check Docker version
        run: docker --version

      # 3. Устанавливаем Yandex Cloud CLI
      - name: Install Yandex Cloud CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH  # исправлен путь
          export PATH="$HOME/yandex-cloud/bin:$PATH"
          yc version

      # 4. Логинимся в Yandex Cloud
      - name: Authenticate Yandex Cloud
        run: |
          export PATH="$HOME/yandex-cloud/bin:$PATH"
          echo '${{ secrets.YC_SERVICE_ACCOUNT_KEY }}' > key.json
          yc config set service-account-key key.json
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}
          # Проверяем аутентификацию
          echo "=== Проверка конфигурации ==="
          yc config list
          echo "=== Проверка аутентификации ==="
          yc iam service-account get $(yc iam key get --key-id $(yc iam key list --format json | jq -r '.[0].id') --format json | jq -r '.service_account_id')

      # 5. Логинимся в Yandex Container Registry
      - name: Login to Yandex Container Registry
        run: |
          export PATH="$HOME/yandex-cloud/bin:$PATH"
          # Проверяем права доступа
          yc container registry list
          # Создаем IAM токен и логинимся
          yc iam create-token | docker login --username iam --password-stdin cr.yandex

      # 6. Pull образ из GitHub Container Registry  
      - name: Pull image from GHCR
        run: docker pull ghcr.io/riestru/nginx_container:latest

      # 7. Tag образ для Yandex Cloud
      - name: Tag image for YC
        run: docker tag ghcr.io/riestru/nginx_container:latest cr.yandex/${{ secrets.YC_REGISTRY_ID }}/nginx-container:latest

      # 8. Проверяем локальные образы
      - name: List local Docker images
        run: docker images

      # 9. Inspect конкретного образа
      - name: Inspect YC tagged image
        run: docker inspect cr.yandex/${{ secrets.YC_REGISTRY_ID }}/nginx-container:latest

      # 10. Push образ в Yandex Container Registry
      - name: Push image to YC
        run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/nginx-container:latest

      # 11. Проверяем наличие образа в реестре
      - name: List images in Yandex Container Registry
        run: |
          export PATH="$HOME/yandex-cloud/bin:$PATH"
          yc container image list --registry-id ${{ secrets.YC_REGISTRY_ID }}

      # 12. Очистка временных файлов
      - name: Cleanup
        if: always()
        run: |
          rm -f key.json token.txt
